/**
 * Aktivitäts-Presets: Einkommensteuererklärung
 * @module utils/presets/einkommensteuererklarung
 */

import { ActivityPreset } from "@/types/stbvv";
import { MIN_OBJECT_VALUES } from "@/constants";

export const einkommensteuererklarungPresets: ActivityPreset[] = [
  { 
    activity: 'Einkommensteuererklärung', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 1', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['EST', 'Einkommensteuer', 'Steuererklärung', 'Mantelbogen'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER  // 8.000 € gemäß § 24 Abs. 1 Nr. 1
  },
  ,
  { 
    activity: 'Einkommensteuer Mantelbogen', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 1', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['EST', 'Mantelbogen', 'Hauptformular', 'Hauptvordruck'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage N (Einkünfte aus nichtselbständiger Arbeit)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage N', 'Arbeitnehmer', 'Lohn', 'Gehalt', 'nichtselbständig'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage V (Vermietung und Verpachtung)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage V', 'Vermietung', 'Verpachtung', 'Miete', 'Immobilien'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage G (Gewerbebetrieb)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage G', 'Gewerbebetrieb', 'Gewerbe', 'Einzelunternehmen'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage S (Einkünfte aus selbständiger Arbeit)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage S', 'Selbständig', 'Freiberufler', 'Freiberuflich'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage KAP (Kapitalerträge)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage KAP', 'Kapitalerträge', 'Zinsen', 'Dividenden', 'Aktien'],
    minObjectValue: MIN_OBJECT_VALUES.UEBERSCHUSSRECHNUNG  // 8.000 € gemäß § 27 Abs. 1
  },
  ,
  { 
    activity: 'Anlage SO (Sonstige Einkünfte)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage SO', 'Sonstige Einkünfte', 'Spekulationsgeschäfte'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage R (Renten)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage R', 'Renten', 'Altersrente', 'Pension'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage L (Land- und Forstwirtschaft)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage L', 'Landwirtschaft', 'Forstwirtschaft', 'Landwirt'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage EÜR (Einnahmen-Überschuss-Rechnung)', 
    defaultTenthRate: 17.5,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 25', 
    rateType: 'tenth', 
    minRate: 5, 
    maxRate: 30,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['EÜR', 'Einnahmen-Überschuss', 'Anlage EÜR', '4/3-Rechnung'],
    minObjectValue: MIN_OBJECT_VALUES.EÜR  // 17.500 € gemäß § 25 StBVV
  },
  ,
  { 
    activity: 'Anlage Kind', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Kind', 'Kindergeld', 'Kinderfreibetrag', 'Kinder'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage AV (Altersvorsorge)', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage AV', 'Altersvorsorge', 'Riester', 'Rürup'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage Unterhalt', 
    defaultTenthRate: 4,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 7,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Unterhalt', 'Unterhaltszahlungen', 'Kindesunterhalt'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage Vorsorgeaufwand', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Vorsorge', 'Versicherungen', 'Krankenversicherung'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage Sonderausgaben', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Sonderausgaben', 'Spenden', 'Kirchensteuer'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage Außergewöhnliche Belastungen', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Außergewöhnliche Belastungen', 'Krankheitskosten', 'Pflegekosten'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  ,
  { 
    activity: 'Anlage Haushaltsnahe Aufwendungen', 
    defaultTenthRate: 2,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27 Abs. 1', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 4,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Haushaltsnahe Dienstleistungen', 'Handwerker', 'Putzhilfe'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  }
];
