
import { ActivityPreset } from "@/types/stbvv";
import { MIN_OBJECT_VALUES } from "@/utils/constants";

export const activityPresets: ActivityPreset[] = [
  { 
    activity: 'Einkommensteuererklärung', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 1', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['EST', 'Einkommensteuer', 'Steuererklärung', 'Mantelbogen'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER  // 8.000 € gemäß § 24 Abs. 1 Nr. 1
  },
  { 
    activity: 'Einkommensteuer Mantelbogen', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 1', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['EST', 'Mantelbogen', 'Hauptformular', 'Hauptvordruck'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage N (Einkünfte aus nichtselbständiger Arbeit)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage N', 'Arbeitnehmer', 'Lohn', 'Gehalt', 'nichtselbständig'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage V (Vermietung und Verpachtung)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage V', 'Vermietung', 'Verpachtung', 'Miete', 'Immobilien'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage G (Gewerbebetrieb)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage G', 'Gewerbebetrieb', 'Gewerbe', 'Einzelunternehmen'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage S (Einkünfte aus selbständiger Arbeit)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage S', 'Selbständig', 'Freiberufler', 'Freiberuflich'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage KAP (Kapitalerträge)', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 14', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage KAP', 'Kapitalerträge', 'Zinsen', 'Dividenden', 'Aktien'],
    minObjectValue: MIN_OBJECT_VALUES.KAPITALERTRAGSTEUER  // 4.000 € gemäß § 24 Abs. 1 Nr. 14
  },
  { 
    activity: 'Anlage SO (Sonstige Einkünfte)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage SO', 'Sonstige Einkünfte', 'Spekulationsgeschäfte'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage R (Renten)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage R', 'Renten', 'Altersrente', 'Pension'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage L (Land- und Forstwirtschaft)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'D', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage L', 'Landwirtschaft', 'Forstwirtschaft', 'Landwirt'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage EÜR (Einnahmen-Überschuss-Rechnung)', 
    defaultTenthRate: 17.5,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 25', 
    rateType: 'tenth', 
    minRate: 5, 
    maxRate: 30,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['EÜR', 'Einnahmen-Überschuss', 'Anlage EÜR', '4/3-Rechnung'],
    minObjectValue: MIN_OBJECT_VALUES.EÜR  // 17.500 € gemäß § 25 StBVV
  },
  { 
    activity: 'Anlage Kind', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Kind', 'Kindergeld', 'Kinderfreibetrag', 'Kinder'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage AV (Altersvorsorge)', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage AV', 'Altersvorsorge', 'Riester', 'Rürup'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage Unterhalt', 
    defaultTenthRate: 4,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 7,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Unterhalt', 'Unterhaltszahlungen', 'Kindesunterhalt'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage Vorsorgeaufwand', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Vorsorge', 'Versicherungen', 'Krankenversicherung'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage Sonderausgaben', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Anlage Sonderausgaben', 'Spenden', 'Kirchensteuer'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage Außergewöhnliche Belastungen', 
    defaultTenthRate: 3,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Außergewöhnliche Belastungen', 'Krankheitskosten', 'Pflegekosten'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Anlage Haushaltsnahe Aufwendungen', 
    defaultTenthRate: 2,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 27', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 4,
    category: 'Einkommensteuererklärung',
    searchKeywords: ['Haushaltsnahe Dienstleistungen', 'Handwerker', 'Putzhilfe'],
    minObjectValue: MIN_OBJECT_VALUES.EINKOMMENSTEUER
  },
  { 
    activity: 'Jahresabschluss GmbH', 
    defaultTenthRate: 25,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 1a', 
    rateType: 'tenth', 
    minRate: 10, 
    maxRate: 40,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Jahresabschluss', 'GmbH', 'Bilanz', 'GuV'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS  // 8.000 € gemäß § 35 StBVV
  },
  { 
    activity: 'Jahresabschluss Einzelunternehmen', 
    defaultTenthRate: 25,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 1a', 
    rateType: 'tenth', 
    minRate: 10, 
    maxRate: 40,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Jahresabschluss', 'Einzelunternehmen', 'Bilanz'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Jahresabschluss Übermittlung an Bundesanzeiger', 
    defaultTenthRate: 25,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 6', 
    rateType: 'tenth', 
    minRate: 10, 
    maxRate: 40,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Bundesanzeiger', 'Offenlegung', 'Veröffentlichung'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Jahresabschluss Übermittlung an das Finanzamt', 
    defaultTenthRate: 25,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 6', 
    rateType: 'tenth', 
    minRate: 10, 
    maxRate: 40,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Finanzamt', 'E-Bilanz', 'Übermittlung'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Überleitung Handelsbilanz nach Steuerbilanz', 
    defaultTenthRate: 8.5,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 4b', 
    rateType: 'tenth', 
    minRate: 5, 
    maxRate: 12,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Überleitung', 'Handelsbilanz', 'Steuerbilanz', 'Mehr-Weniger-Rechnung'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Buchführung (monatlich)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'C', 
    legalBasis: '§ 33', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Buchführung', 'Fibu', 'Buchhaltung', 'Belege'],
    minObjectValue: MIN_OBJECT_VALUES.BUCHFÜHRUNG  // 15.000 € gemäß § 33 StBVV
  },
  { 
    activity: 'E-Bilanz Übermittlung', 
    defaultTenthRate: 2,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 6', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 3,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['E-Bilanz', 'Elektronische Bilanz', 'XBRL', 'Taxonomie'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Liquidationsbilanz', 
    defaultTenthRate: 25,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 1b', 
    rateType: 'tenth', 
    minRate: 10, 
    maxRate: 40,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Liquidation', 'Liquidationsbilanz', 'Auflösung', 'Schlussbilanz'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Umsatzsteuer-Voranmeldung', 
    defaultTenthRate: 4.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 7', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Umsatzsteuer',
    searchKeywords: ['UVA', 'Umsatzsteuer', 'Voranmeldung', 'USt-VA', 'Mehrwertsteuer'],
    minObjectValue: MIN_OBJECT_VALUES.UST_VORANMELDUNG  // 650 € gemäß § 24 Abs. 1 Nr. 7
  },
  { 
    activity: 'Umsatzsteuererklärung', 
    defaultTenthRate: 4.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 8', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 8,
    category: 'Umsatzsteuer',
    searchKeywords: ['USt', 'Umsatzsteuer', 'Jahreserklärung', 'Mehrwertsteuer'],
    minObjectValue: MIN_OBJECT_VALUES.UST_JAHRESERKLAERUNG  // 8.000 € gemäß § 24 Abs. 1 Nr. 8
  },
  { 
    activity: 'Zusammenfassende Meldung (ZM)', 
    defaultTenthRate: 2,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 8', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 3,
    category: 'Umsatzsteuer',
    searchKeywords: ['ZM', 'Zusammenfassende Meldung', 'Innergemeinschaftlich', 'EU'],
    minObjectValue: MIN_OBJECT_VALUES.UST_JAHRESERKLAERUNG
  },
  { 
    activity: 'Gewerbesteuererklärung', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 5', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Gewerbe- & Körperschaftsteuer',
    searchKeywords: ['GewSt', 'Gewerbesteuer', 'Gemeinde'],
    minObjectValue: MIN_OBJECT_VALUES.GEWERBESTEUER  // 8.000 € gemäß § 24 Abs. 1 Nr. 5
  },
  { 
    activity: 'Gewerbesteuerzerlegungserklärung', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 6', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Gewerbe- & Körperschaftsteuer',
    searchKeywords: ['Zerlegung', 'Gewerbesteuer', 'Arbeitslöhne'],
    minObjectValue: MIN_OBJECT_VALUES.GEWERBESTEUER_ZERLEGUNG  // 4.000 € gemäß § 24 Abs. 1 Nr. 6
  },
  { 
    activity: 'Körperschaftsteuererklärung', 
    defaultTenthRate: 5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 3', 
    rateType: 'tenth', 
    minRate: 2, 
    maxRate: 8,
    category: 'Gewerbe- & Körperschaftsteuer',
    searchKeywords: ['KSt', 'Körperschaftsteuer', 'GmbH', 'Kapitalgesellschaft'],
    minObjectValue: MIN_OBJECT_VALUES.KOERPERSCHAFTSTEUER  // 16.000 € gemäß § 24 Abs. 1 Nr. 3
  },
  { 
    activity: 'Beratung allgemein', 
    defaultTenthRate: 100,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 23 Abs. 1', 
    rateType: 'tenth', 
    minRate: 50, 
    maxRate: 200,
    category: 'Beratungsleistungen',
    searchKeywords: ['Beratung', 'Consulting', 'Gespräch', 'Besprechung'],
    minObjectValue: 0  // Stundenbasiert, kein Mindestgegenstandswert
  },
  { 
    activity: 'Beratung bei Betriebseröffnung/-übernahme', 
    defaultTenthRate: 120,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 23 Abs. 3', 
    rateType: 'tenth', 
    minRate: 80, 
    maxRate: 200,
    category: 'Beratungsleistungen',
    searchKeywords: ['Betriebseröffnung', 'Existenzgründung', 'Betriebsübernahme', 'Gründung'],
    minObjectValue: 0
  },
  { 
    activity: 'Beratung bei Umstrukturierung', 
    defaultTenthRate: 120,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 23 Abs. 3', 
    rateType: 'tenth', 
    minRate: 80, 
    maxRate: 200,
    category: 'Beratungsleistungen',
    searchKeywords: ['Umstrukturierung', 'Umwandlung', 'Rechtsformwechsel'],
    minObjectValue: 0
  },
  { 
    activity: 'Schriftliche Gutachten', 
    defaultTenthRate: 150,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 23 Abs. 4', 
    rateType: 'tenth', 
    minRate: 100, 
    maxRate: 250,
    category: 'Beratungsleistungen',
    searchKeywords: ['Gutachten', 'Stellungnahme', 'Expertise'],
    minObjectValue: 0
  },
  { 
    activity: 'Betriebswirtschaftliche Beratung', 
    defaultTenthRate: 120,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 35 Abs. 2', 
    rateType: 'tenth', 
    minRate: 80, 
    maxRate: 200,
    category: 'Beratungsleistungen',
    searchKeywords: ['BWA', 'Betriebswirtschaft', 'Controlling', 'Kennzahlen'],
    minObjectValue: 0
  },
  { 
    activity: 'Finanzplanung und Liquiditätsplanung', 
    defaultTenthRate: 100,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 35 Abs. 2', 
    rateType: 'tenth', 
    minRate: 60, 
    maxRate: 180,
    category: 'Beratungsleistungen',
    searchKeywords: ['Finanzplanung', 'Liquidität', 'Cashflow', 'Planung'],
    minObjectValue: 0
  },
  { 
    activity: 'Steuerschätzung', 
    defaultTenthRate: 100,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 22', 
    rateType: 'tenth', 
    minRate: 60, 
    maxRate: 180,
    category: 'Beratungsleistungen',
    searchKeywords: ['Schätzung', 'Steuerberechnung', 'Prognose'],
    minObjectValue: 0
  },
  { 
    activity: 'Einspruch beim Finanzamt', 
    defaultTenthRate: 4.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 40 Abs. 1', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 8,
    category: 'Rechtsbehelfsverfahren',
    searchKeywords: ['Einspruch', 'Widerspruch', 'Rechtsbehelf'],
    minObjectValue: MIN_OBJECT_VALUES.SONSTIGE
  },
  { 
    activity: 'Aussetzung der Vollziehung (AdV)', 
    defaultTenthRate: 4.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 40 Abs. 1', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 8,
    category: 'Rechtsbehelfsverfahren',
    searchKeywords: ['AdV', 'Aussetzung', 'Vollziehung', 'Stundung'],
    minObjectValue: MIN_OBJECT_VALUES.SONSTIGE
  },
  { 
    activity: 'Prüfung Steuerbescheid', 
    defaultTenthRate: 0,
    defaultHourlyRate: 115,  // Stand: 01.07.2025
    suggestedFeeTable: 'A', 
    legalBasis: '§ 13 StBVV (Zeitgebühr ab 01.07.2025)', 
    rateType: 'hourly', 
    minRate: 0, 
    maxRate: 0,
    category: 'Rechtsbehelfsverfahren',
    searchKeywords: ['Steuerbescheid', 'Prüfung', 'Bescheidprüfung', 'Kontrolle'],
    minObjectValue: 0  // Zeitgebühr, kein Gegenstandswert
  },
  { 
    activity: 'Erbschaftsteuererklärung', 
    defaultTenthRate: 6,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 12', 
    rateType: 'tenth', 
    minRate: 2, 
    maxRate: 10,
    category: 'Erbschaft- & Schenkungsteuer',
    searchKeywords: ['ErbSt', 'Erbschaftsteuer', 'Erbe', 'Nachlass'],
    minObjectValue: MIN_OBJECT_VALUES.ERBSCHAFTSTEUER  // 16.000 € gemäß § 24 Abs. 1 Nr. 12
  },
  { 
    activity: 'Schenkungsteuererklärung', 
    defaultTenthRate: 6,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 13', 
    rateType: 'tenth', 
    minRate: 2, 
    maxRate: 10,
    category: 'Erbschaft- & Schenkungsteuer',
    searchKeywords: ['SchenkSt', 'Schenkungsteuer', 'Schenkung'],
    minObjectValue: MIN_OBJECT_VALUES.SCHENKUNGSTEUER  // 16.000 € gemäß § 24 Abs. 1 Nr. 13
  },
  { 
    activity: 'Feststellung nach Bewertungsgesetz', 
    defaultTenthRate: 9,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 11', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 18,
    category: 'Erbschaft- & Schenkungsteuer',
    searchKeywords: ['Bewertung', 'Feststellung', 'Grundbesitzwert'],
    minObjectValue: MIN_OBJECT_VALUES.FESTSTELLUNG_BEWERTUNG  // 25.000 € gemäß § 24 Abs. 1 Nr. 11
  },
  { 
    activity: 'Grundsteuererklärung', 
    defaultTenthRate: 5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 11a', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 9,
    category: 'Sonstige Steuererklärungen',
    searchKeywords: ['Grundsteuer', 'Grundsteuerwert', 'Grundsteuermessbetrag'],
    minObjectValue: MIN_OBJECT_VALUES.GRUNDSTEUER  // 25.000 € gemäß § 24 Abs. 1 Nr. 11a
  },
  { 
    activity: 'Grunderwerbsteuererklärung', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 26', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Sonstige Steuererklärungen',
    searchKeywords: ['GrESt', 'Grunderwerbsteuer', 'Immobilienkauf', 'Grundstück'],
    minObjectValue: MIN_OBJECT_VALUES.SONSTIGE  // 8.000 € gemäß § 24 Abs. 1 Nr. 26
  },
  { 
    activity: 'Antrag auf Feststellung des verbleibenden Verlustvortrags', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 26', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Sonstige Steuererklärungen',
    searchKeywords: ['Verlustvortrag', 'Feststellungserklärung', 'Verlust'],
    minObjectValue: MIN_OBJECT_VALUES.SONSTIGE
  },
  { 
    activity: 'Gesonderte und einheitliche Feststellung', 
    defaultTenthRate: 5.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 2', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 5,
    category: 'Sonstige Steuererklärungen',
    searchKeywords: ['Feststellungserklärung', 'GuE', 'Personengesellschaft', 'Mitunternehmerschaft'],
    minObjectValue: MIN_OBJECT_VALUES.GESONDERTE_FESTSTELLUNG  // 8.000 € gemäß § 24 Abs. 1 Nr. 2
  },
  { 
    activity: 'Betriebsprüfung begleiten', 
    defaultTenthRate: 100,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 29', 
    rateType: 'tenth', 
    minRate: 50, 
    maxRate: 180,
    category: 'Rechtsbehelfsverfahren',
    searchKeywords: ['Betriebsprüfung', 'Außenprüfung', 'Prüfer', 'Finanzamt'],
    minObjectValue: 0  // Stundenbasiert
  },
  { 
    activity: 'Überleitungsrechnung (§ 60 Abs. 3 EStG)', 
    defaultTenthRate: 8.5,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 4b', 
    rateType: 'tenth', 
    minRate: 2, 
    maxRate: 15,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Überleitungsrechnung', 'Anlageverzeichnis', 'Steuerbilanz'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Elektronische Übermittlung Bundesanzeiger', 
    defaultTenthRate: 2,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 6', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 3,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['E-Bilanz', 'Bundesanzeiger', 'Elektronische Übermittlung', 'Offenlegung'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Elektronische Übermittlung Finanzamt', 
    defaultTenthRate: 2,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 6', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 3,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['E-Bilanz', 'Finanzamt', 'Elektronische Übermittlung', 'ELSTER'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Jahresabschluss (Kapitalgesellschaften)', 
    defaultTenthRate: 25,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 1a', 
    rateType: 'tenth', 
    minRate: 10, 
    maxRate: 40,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Jahresabschluss', 'GmbH', 'AG', 'Kapitalgesellschaft', 'Bilanz'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS
  },
  { 
    activity: 'Lohnbuchhaltung', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'C', 
    legalBasis: '§ 33', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Lohnbuchhaltung',
    searchKeywords: ['Lohnbuchhaltung', 'Lohn', 'Gehalt', 'Personalabrechnung'],
    minObjectValue: MIN_OBJECT_VALUES.LOHNBUCHHALTUNG
  },
  { 
    activity: 'Lohnabrechnung pro Arbeitnehmer (monatlich)', 
    defaultTenthRate: 15,
    suggestedFeeTable: 'C', 
    legalBasis: '§ 34 Abs. 1', 
    rateType: 'tenth', 
    minRate: 10, 
    maxRate: 25,
    category: 'Lohnbuchhaltung',
    searchKeywords: ['Lohnabrechnung', 'Gehaltsabrechnung', 'Mitarbeiter'],
    minObjectValue: MIN_OBJECT_VALUES.LOHNBUCHHALTUNG
  },
  { 
    activity: 'Anmeldung Lohnsteuer', 
    defaultTenthRate: 2.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 15', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Lohnbuchhaltung',
    searchKeywords: ['Lohnsteueranmeldung', 'Lohnsteuer', 'LSt'],
    minObjectValue: MIN_OBJECT_VALUES.LOHNSTEUER_ANMELDUNG  // 1.000 € gemäß § 24 Abs. 1 Nr. 15
  },
  { 
    activity: 'Lohnsteuer-Ermäßigung', 
    defaultTenthRate: 2.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 4', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 4,
    category: 'Lohnbuchhaltung',
    searchKeywords: ['Lohnsteuer-Ermäßigung', 'Freibetrag', 'Eintragung'],
    minObjectValue: MIN_OBJECT_VALUES.LOHNSTEUER_ERMAESSIGUNG  // 4.500 € gemäß § 24 Abs. 4
  },
  { 
    activity: 'Kapitalertragsteueranmeldung', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 14', 
    rateType: 'twentieth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Sonstige Steuererklärungen',
    searchKeywords: ['Kapitalertragsteuer', 'KapESt', 'Dividenden'],
    minObjectValue: MIN_OBJECT_VALUES.KAPITALERTRAGSTEUER  // 4.000 € gemäß § 24 Abs. 1 Nr. 14
  },
  { 
    activity: 'Antrag auf Vorsteuer-Vergütung', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 21', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Umsatzsteuer',
    searchKeywords: ['Vorsteuer', 'Vergütung', 'Erstattung'],
    minObjectValue: MIN_OBJECT_VALUES.VORSTEUER_VERGUETUNG  // 1.300 € gemäß § 24 Abs. 1 Nr. 21
  },
  { 
    activity: 'Fristverlängerung beantragen', 
    defaultTenthRate: 80,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 23', 
    rateType: 'tenth', 
    minRate: 50, 
    maxRate: 150,
    category: 'Sonstige Tätigkeiten',
    searchKeywords: ['Fristverlängerung', 'Frist', 'Verlängerung', 'Antrag'],
    minObjectValue: 0  // Stundenbasiert
  },
  { 
    activity: 'Bescheinigungen ausstellen', 
    defaultTenthRate: 80,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 23', 
    rateType: 'tenth', 
    minRate: 50, 
    maxRate: 150,
    category: 'Sonstige Tätigkeiten',
    searchKeywords: ['Bescheinigung', 'Bestätigung', 'Nachweis'],
    minObjectValue: 0  // Stundenbasiert
  },
  { 
    activity: 'Auslagen für externe Kosten', 
    defaultTenthRate: 5.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 1 Nr. 1', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 10,
    category: 'Sonstige Tätigkeiten',
    searchKeywords: ['Auslagen', 'Kosten', 'Spesen', 'Porto'],
    minObjectValue: 0
  },
  { 
    activity: 'Ermittlung Zugewinnausgleichsforderung (§ 5 ErbStG)', 
    defaultTenthRate: 10,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 24 Abs. 3', 
    rateType: 'tenth', 
    minRate: 5, 
    maxRate: 15,
    category: 'Erbschaft- & Schenkungsteuer',
    searchKeywords: ['Zugewinn', 'Zugewinnausgleich', 'ErbStG'],
    minObjectValue: MIN_OBJECT_VALUES.ZUGEWINNAUSGLEICH  // 12.500 €
  },
  { 
    activity: 'Jahresabschluss (Personengesellschaften)', 
    defaultTenthRate: 17.5,
    suggestedFeeTable: 'B', 
    legalBasis: '§ 35 Abs. 1 Nr. 1a', 
    rateType: 'tenth', 
    minRate: 5, 
    maxRate: 30,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Jahresabschluss', 'GbR', 'OHG', 'KG', 'Personengesellschaft'],
    minObjectValue: MIN_OBJECT_VALUES.JAHRESABSCHLUSS  // 17.500 €
  },
  { 
    activity: 'Kontieren der Belege', 
    defaultTenthRate: 3.5,
    suggestedFeeTable: 'C', 
    legalBasis: '§ 33 Abs. 2', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 6,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Kontieren', 'Belege', 'Vorkontierung'],
    minObjectValue: MIN_OBJECT_VALUES.BUCHFÜHRUNG  // 15.000 €
  },
  { 
    activity: 'Lohnkonto', 
    defaultTenthRate: 7.5,
    suggestedFeeTable: 'C', 
    legalBasis: '§ 34 Abs. 2', 
    rateType: 'tenth', 
    minRate: 5, 
    maxRate: 10,
    category: 'Lohnbuchhaltung',
    searchKeywords: ['Lohnkonto', 'Jahreslohnkonto', 'Arbeitnehmer'],
    minObjectValue: MIN_OBJECT_VALUES.LOHNBUCHHALTUNG  // 1.000 €
  },
  { 
    activity: 'Anpassungsantrag', 
    defaultTenthRate: 4.5,
    suggestedFeeTable: 'A', 
    legalBasis: '§ 40 Abs. 1 StBVV', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 8,
    category: 'Rechtsbehelfsverfahren',
    searchKeywords: ['Anpassungsantrag', 'Änderungsantrag', '§ 164 AO', '§ 172 AO', 'Änderung'],
    minObjectValue: MIN_OBJECT_VALUES.SONSTIGE
  },
  { 
    activity: 'Erstberatung', 
    defaultTenthRate: 0,
    defaultHourlyRate: 190,  // Pauschalhonorar max. 190 € gemäß § 21 StBVV
    suggestedFeeTable: 'A', 
    legalBasis: '§ 21 StBVV', 
    rateType: 'hourly', 
    minRate: 0, 
    maxRate: 0,
    category: 'Beratungsleistungen',
    searchKeywords: ['Erstberatung', 'Erstgespräch', 'Erstberatungsgespräch', 'Kennenlern'],
    minObjectValue: 0  // Zeitgebühr
  },
  { 
    activity: 'Buchführung (quartal)', 
    defaultTenthRate: 6.5,
    suggestedFeeTable: 'C', 
    legalBasis: '§ 33', 
    rateType: 'tenth', 
    minRate: 1, 
    maxRate: 12,
    category: 'Jahresabschluss & Buchführung',
    searchKeywords: ['Buchführung', 'Fibu', 'Buchhaltung', 'quartal', 'vierteljährlich'],
    minObjectValue: MIN_OBJECT_VALUES.BUCHFÜHRUNG
  }
];

export const getActivityPreset = (activity: string): ActivityPreset | undefined => {
  return activityPresets.find(preset => preset.activity === activity);
};
